version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    networks:
      - app_network

  frontend:
    build:
      context: ./my-app/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

  db_postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: product
    networks:
      - app_network
    

  caddy_server:
    image: caddy:latest
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
