version: '3'
services:
  backend:
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    networks:
      - default

  frontend:
    build:
      context: ./front-end/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default

  db_postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default
    

  caddy_server:
    image: caddy:2.7
    restart: always
    volumes:
      - ./back-end/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - default
    
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
        NGROK_PROTOCOL: http
        NGROK_PORT: caddy_server:8080
        NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - caddy_server
    networks:
      - default

networks:
  default:
    driver: bridge
