name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    docker container run -it -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/containers:/var/lib/docker/containers:ro -e ACCOUNT_UUID={781a5786-67df-42e1-b21c-4fba13f36a6a}  -e RUNNER_UUID={f02f87d1-faa1-5690-8055-81718f4f82fc} -e RUNTIME_PREREQUISITES_ENABLED=true -e OAUTH_CLIENT_ID=MaTY6NJBjSvIsn3qqGuq4MCJrpbeCZSI -e OAUTH_CLIENT_SECRET=ATOAZSlj1Qmy-JXIHM844-wXoQqkZxoUC8OPnHOQjwObBYPw-jC_n3sagpArYgI7ZlZE3FB9F0D4 -e WORKING_DIRECTORY=/tmp --name runner-f02f87d1-faa1-5690-8055-81718f4f82fc docker-public.packages.atlassian.com/sox/atlassian/bitbucket-pipelines-runner:1

    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
